services:
  - type: web
    name: webdemo
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/webdemo-1.0.0.jar --spring.profiles.active=prod
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: PORT
        value: 10005
    healthCheckPath: /actuator/health
